# Generated by Django 4.2.3 on 2023-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(null='false'),
        ),
    ]
